### ISSUE TITLE
CSS improvement

### ISSUE THREAD

**Issue by Jordy3D** [evilarceus/Destiny2-Soundboard#1]
Honestly not too sure where to put this, but I saw your comment on Reddit mentioning the CSS so I made it look at least somewhat more like the Drifter soundboard (no mouse hover stuff or anything though)

Just in case you wanted it:
```css
.red.darken-3 {
    background-color: #000000 !important;
    border: 1px solid hsla(0,0%,100%,.5);
    border-width: .5px !important;
    border-radius: 0px !important;
}

.sound-btn {
    margin: 10px;
    border: 1px solid hsla(0,0%,100%,.5);
    width: 250px;
    height: 50px;
    justify-content: center;
}
```
![image](https://user-images.githubusercontent.com/19144524/56289903-6411f380-6165-11e9-9d4a-5dc3fe6f3c6c.png)
